[package]
name = "serializer-tests"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move serializer tests"

[dev-dependencies]
# external dependencies
proptest.workspace = true
proptest-derive.workspace = true

# internal dependencies
move-binary-format = { workspace = true, features = ["fuzzing"] }

[features]
fuzzing = ["move-binary-format/fuzzing"]

[dependencies]
