[package]
name = "move-binary-format"
version = "0.0.3"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = ["crates-io"]
description = "Move Binary Format"

[dependencies]
# external dependencies
anyhow.workspace = true
arbitrary = { workspace = true, optional = true, features = ["derive"] }
# wasm support (requires js feature of getrandom)
getrandom = { workspace = true, features = ["js"], optional = true }
indexmap.workspace = true
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
ref-cast.workspace = true
serde.workspace = true
variant_count.workspace = true

# internal dependencies
enum-compat-util.workspace = true
move-core-types.workspace = true
move-proc-macros.workspace = true

[dev-dependencies]
# external dependencies
proptest.workspace = true
proptest-derive.workspace = true

# internal dependencies
move-core-types = { workspace = true, features = ["fuzzing"] }

[features]
default = []
fuzzing = [
  "arbitrary",
  "move-core-types/fuzzing",
  "proptest",
  "proptest-derive",
]
wasm = ["getrandom"]

[package.metadata.cargo-udeps.ignore]
normal = ["enum-compat-util"]
