[package]
name = "suilend"
version = "0.0.1"
published-at = "0xd1ad8c401da6933bb5a5ccde1420f35c45e6a42a79ea6003f3248fe3c510d418"
edition = "2024.beta"
 
[dependencies.Pyth]
git = "https://github.com/solendprotocol/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "73b2a5a9786d54ca1341f43bcddd90040a325b4c"

[dependencies.liquid_staking]
git = "https://github.com/solendprotocol/liquid-staking.git"
subdir = "contracts"
rev = "main"

[dependencies.sprungsui]
local = "../sprungsui"

[addresses]
sui = "0x2"
# suilend = "0x0"
suilend = "0x1f54a9a2d71799553197e9ea24557797c6398d6a65f2d4d3818c9304b75d5e21"
