[package]
name = "move-docgen-tests"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
# external dependencies
anyhow.workspace = true
codespan.workspace = true
codespan-reporting.workspace = true
insta.workspace = true
itertools.workspace = true
log.workspace = true
num.workspace = true
once_cell.workspace = true
regex.workspace = true
serde.workspace = true
tempfile.workspace = true

# internal dependencies
move-binary-format.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-docgen.workspace = true
move-ir-types.workspace = true
move-model-2.workspace = true
move-package.workspace = true
move-symbol-pool.workspace = true

[dev-dependencies]
datatest-stable.workspace = true

[[test]]
name = "testsuite"
harness = false
