[package]
name = "shared-with-tto"
version = "0.0.1"
edition = "2024"

[dependencies]
Iota = { local = "../../../../crates/iota-framework/packages/iota-framework" }
common = { local = "../common" }

[addresses]
shared_with_tto = "0x0"
