[package]
name = "generic_keyed_authentication"
edition = "2024"

[dependencies]
Iota = { local = "../../../crates/iota-framework/packages/iota-framework" }

[addresses]
generic_keyed_authentication = "0x0"

[dev-dependencies]

[dev-addresses]
