[package]
name = "move-ir-compiler"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move IR to bytecode compiler"

[dependencies]
# external dependencies
anyhow.workspace = true
bcs.workspace = true
clap.workspace = true
serde_json.workspace = true

# internal dependencies
move-abstract-interpreter.workspace = true
move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-bytecode-verifier.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-ir-to-bytecode.workspace = true

[features]
default = []
