[dependencies]
anyhow = { workspace = true }
move-model = { git = "https://github.com/starcoinorg/move", rev = "2a1550807cd28cdc04e3bf19576c9a2958864243" }
starcoin-vm2-abi-types = { workspace = true }
starcoin-vm2-resource-viewer = { workspace = true }
starcoin-vm2-vm-types = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
starcoin-cached-packages = { path = "../../framework/cached-packages" }
test-helper = { path = "../../../vm2/test-helper", package = "starcoin-test-helper" }

[package]
authors = { workspace = true }
edition = { workspace = true }
name = "starcoin-vm2-abi-resolver"
version = "2.0.1"
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
