[package]
name = "iota-transactional-test-runner"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move framework for IOTA platform"

[lints]
workspace = true

[dependencies]
# external dependencies
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bcs.workspace = true
bimap = "0.6"
clap.workspace = true
criterion.workspace = true
eyre.workspace = true
fastcrypto.workspace = true
http.workspace = true
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
tempfile.workspace = true
tokio.workspace = true

# internal dependencies
iota-config.workspace = true
iota-core.workspace = true
iota-framework.workspace = true
iota-graphql-rpc.workspace = true
iota-json-rpc.workspace = true
iota-json-rpc-api.workspace = true
iota-json-rpc-types.workspace = true
iota-protocol-config.workspace = true
iota-storage.workspace = true
iota-swarm-config.workspace = true
iota-types.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-stdlib = { path = "../../external-crates/move/crates/move-stdlib" }
move-symbol-pool.workspace = true
move-transactional-test-runner = { path = "../../external-crates/move/crates/move-transactional-test-runner" }
move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }
simulacrum.workspace = true
telemetry-subscribers.workspace = true
typed-store.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true

[package.metadata.cargo-machete]
ignored = [
  "eyre", # imported through a procedural macro
]
