[package]
name = "test-cluster"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
# external dependencies
anyhow.workspace = true
futures.workspace = true
jsonrpsee.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

# internal dependencies
iota-common.workspace = true
iota-config.workspace = true
iota-core.workspace = true
iota-framework.workspace = true
iota-genesis-builder.workspace = true
iota-json-rpc.workspace = true
iota-json-rpc-api.workspace = true
iota-json-rpc-types.workspace = true
iota-keys.workspace = true
iota-node.workspace = true
iota-protocol-config.workspace = true
iota-sdk.workspace = true
iota-swarm.workspace = true
iota-swarm-config.workspace = true
iota-test-transaction-builder.workspace = true
iota-types.workspace = true
move-binary-format.workspace = true

[target.'cfg(msim)'.dependencies]
# external dependencies
fastcrypto-zkp.workspace = true
prometheus.workspace = true

# internal dependencies
iota-simulator.workspace = true

[dev-dependencies]
iota-json-rpc-api.workspace = true
iota-macros.workspace = true
iota-metrics.workspace = true
