[package]
name = "starcoin-move-stdlib"
version = "0.1.1"
edition = "2021"
authors = ["Starcoin Association <opensource@starcoinorg.com>"]
description = "Starcoin stdlib"
repository = "https://github.com/starcoinorg/starcoin"
homepage = "https://starcoin.org"
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = { workspace = true }
include_dir = { workspace = true }
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "2a1550807cd28cdc04e3bf19576c9a2958864243" }
move-vm-runtime = { git = "https://github.com/starcoinorg/move", rev = "2a1550807cd28cdc04e3bf19576c9a2958864243" }
move-vm-types = { git = "https://github.com/starcoinorg/move", rev = "2a1550807cd28cdc04e3bf19576c9a2958864243" }
once_cell = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
smallvec = { workspace = true }
starcoin-gas-schedule = { path = "../gas-schedule" }
starcoin-logger = { workspace = true }
starcoin-native-interface = { path = "../native-interface" }
tempfile = { workspace = true }

[dev-dependencies]
dir-diff = "0.3.2"
file_diff = "1.0.0"
tempfile = { workspace = true }

[features]
testing = []
