[package]
name = "move-compiler-transactional-tests"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dev-dependencies]
# external dependencies
datatest-stable.workspace = true

# internal dependencies
move-transactional-test-runner.workspace = true

[[test]]
name = "tests"
harness = false

[dependencies]
