[package]
name = "evm-to-move"
edition = "2024"

[dependencies]
Iota = { local = "../../../../crates/iota-framework/packages/iota-framework" }
Stardust = { local = "../../../../crates/iota-framework/packages/stardust" }

[addresses]
example = "0x0"
