[package]
name = "iota-source-validation-service"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "iota-source-validation-service"

[dependencies]
# external dependencies
anyhow = { workspace = true, features = ["backtrace"] }
axum.workspace = true
clap.workspace = true
hyper.workspace = true
prometheus.workspace = true
serde.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
toml.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
url.workspace = true

# internal dependencies
bin-version.workspace = true
iota-metrics.workspace = true
iota-move.workspace = true
iota-move-build.workspace = true
iota-package-management.workspace = true
iota-sdk.workspace = true
iota-source-validation.workspace = true
move-core-types.workspace = true
move-package.workspace = true
move-symbol-pool.workspace = true
telemetry-subscribers.workspace = true

[dev-dependencies]
# external dependencies
expect-test.workspace = true
fs_extra.workspace = true
reqwest.workspace = true

# internal dependencies
iota.workspace = true
iota-json-rpc-types.workspace = true
iota-move.workspace = true
test-cluster.workspace = true
