[package]
name = "move-compiler"
version = "0.0.1"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "The definition of the Move source language, and its compiler"

[dependencies]
# external dependencies
anyhow.workspace = true
bcs.workspace = true
clap.workspace = true
codespan-reporting.workspace = true
dunce.workspace = true
hex.workspace = true
insta.workspace = true
lsp-types.workspace = true
once_cell.workspace = true
petgraph.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
similar.workspace = true
stacker.workspace = true
tempfile.workspace = true
vfs.workspace = true

# internal dependencies
move-binary-format.workspace = true
move-borrow-graph.workspace = true
move-bytecode-source-map.workspace = true
move-bytecode-verifier.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-ir-to-bytecode.workspace = true
move-ir-types.workspace = true
move-proc-macros.workspace = true
move-symbol-pool.workspace = true

[dev-dependencies]
# external dependencies
datatest-stable.workspace = true

# internal dependencies
move-stdlib.workspace = true

[[test]]
name = "move_check_testsuite"
harness = false
