[package]
name = "iota"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Bringing the real world to Web3 with a scalable, decentralized and programmable DLT infrastructure"

[lints]
workspace = true

[dependencies]
# external dependencies
anemo.workspace = true
anyhow.workspace = true
async-recursion.workspace = true
async-trait.workspace = true
aws-config.workspace = true
aws-sdk-kms = "1.44.0"
bcs.workspace = true
bip32.workspace = true
blake2 = { version = "0.10", optional = true }
camino.workspace = true
chrono = { workspace = true, optional = true }
clap.workspace = true
clap_complete = { version = "4.5", optional = true }
colored.workspace = true
csv.workspace = true
fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
futures.workspace = true
http.workspace = true
inquire = "0.6.0"
json_to_table.workspace = true
miette = { version = "7", features = ["fancy"] }
prometheus.workspace = true
rand.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
signature.workspace = true
strum.workspace = true
tabled.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
url.workspace = true

# internal dependencies
bin-version.workspace = true
iota-config.workspace = true
iota-execution.workspace = true
iota-faucet.workspace = true
iota-genesis-builder.workspace = true
iota-graphql-rpc = { workspace = true, optional = true }
iota-graphql-rpc-client = { workspace = true, optional = true }
iota-indexer = { workspace = true, optional = true }
iota-json.workspace = true
iota-json-rpc-types.workspace = true
iota-keys.workspace = true
iota-ledger.workspace = true
iota-ledger-signer.workspace = true
iota-move.workspace = true
iota-move-build.workspace = true
iota-names = { workspace = true, optional = true }
iota-package-management.workspace = true
iota-protocol-config.workspace = true
iota-replay.workspace = true
iota-sdk.workspace = true
iota-sdk-types.workspace = true
iota-source-validation.workspace = true
iota-swarm.workspace = true
iota-swarm-config.workspace = true
iota-types.workspace = true
move-analyzer.workspace = true
move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-bytecode-verifier-meter.workspace = true
move-cli.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-ir-types.workspace = true
move-package.workspace = true
move-symbol-pool.workspace = true
move-vm-profiler.workspace = true
telemetry-subscribers.workspace = true

[target.'cfg(not(msim))'.dev-dependencies]
datatest-stable.workspace = true

[dev-dependencies]
# external dependencies
assert_cmd = "2.0.6"
expect-test.workspace = true
fs_extra.workspace = true
insta.workspace = true
insta-cmd = "0.6"
prometheus.workspace = true
serde_json.workspace = true
shlex = "1.3.0"
toml.workspace = true

# internal dependencies
iota-macros.workspace = true
iota-metrics.workspace = true
iota-simulator.workspace = true
iota-test-transaction-builder.workspace = true
move-cli.workspace = true
test-cluster.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true

[[example]]
name = "generate-genesis-checkpoint"
path = "src/generate_genesis_checkpoint.rs"
test = false

[[test]]
name = "ptb_files_tests"
harness = false

[[test]]
name = "shell_tests"
harness = false

[features]
gen-completions = ["dep:clap_complete"]
indexer = ["dep:iota-indexer", "dep:iota-graphql-rpc"]
iota-names = [
  "dep:blake2",
  "dep:chrono",
  "dep:iota-graphql-rpc-client",
  "dep:iota-names",
  "iota-sdk/iota-names",
]
tracing = ["iota-types/tracing", "iota-execution/tracing", "iota-move/tracing"]
