[package]
name = "iota-rest-api"
version.workspace = true
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
# external dependencies
anyhow.workspace = true
axum.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
itertools.workspace = true
mime.workspace = true
openapiv3 = { git = "https://github.com/bmwill/openapiv3.git", rev = "ca4b4845b7c159a39f5c68ad8f7f76cb6f4d6963" }
prometheus.workspace = true
reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
tap.workspace = true
tokio.workspace = true
url.workspace = true

# internal dependencies
iota-network-stack.workspace = true
iota-protocol-config.workspace = true
iota-sdk-types.workspace = true
iota-types.workspace = true
move-binary-format.workspace = true

[dev-dependencies]
diffy.workspace = true
