[package]
name = "move-command-line-common"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move shared command line and file tools"

[dependencies]
# external dependencies
anyhow.workspace = true
bcs.workspace = true
dirs-next.workspace = true
hex.workspace = true
insta = { workspace = true, features = ["serde"] }
once_cell.workspace = true
packed_struct.workspace = true
serde.workspace = true
sha2.workspace = true
vfs.workspace = true
walkdir.workspace = true

# internal dependencies
move-binary-format.workspace = true
move-core-types.workspace = true

[dev-dependencies]
proptest.workspace = true
