[package]
name = "iota-adapter-latest"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Adapter and accompanying CLI for local iota development"

[lints]
workspace = true

[dependencies]
# external dependencies
anyhow = { workspace = true, features = ["backtrace"] }
bcs.workspace = true
leb128 = "0.2.5"
parking_lot.workspace = true
serde.workspace = true
tracing.workspace = true

# internal dependencies
iota-macros.workspace = true
iota-metrics.workspace = true
iota-move-natives = { path = "../iota-move-natives", package = "iota-move-natives-latest" }
iota-protocol-config.workspace = true
iota-types.workspace = true
iota-verifier = { path = "../iota-verifier", package = "iota-verifier-latest" }
move-binary-format.workspace = true
move-bytecode-verifier = { path = "../../../external-crates/move/crates/move-bytecode-verifier" }
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-trace-format.workspace = true
move-vm-config.workspace = true
move-vm-profiler = { path = "../../../external-crates/move/crates/move-vm-profiler" }
move-vm-runtime = { path = "../../../external-crates/move/crates/move-vm-runtime" }
move-vm-types = { path = "../../../external-crates/move/crates/move-vm-types" }

[features]
tracing = [
  "iota-types/tracing",
  "move-vm-config/tracing",
  "move-vm-profiler/tracing",
  "move-vm-runtime/tracing",
]
