[package]
name = "iota-rest-kv"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
# external dependencies
anyhow.workspace = true
aws-config.workspace = true
aws-sdk-dynamodb.workspace = true
axum.workspace = true
base64-url.workspace = true
bcs.workspace = true
bytes.workspace = true
clap = { workspace = true, features = ["env"] }
object_store.workspace = true
rustls.workspace = true
serde.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

# internal dependencies
bin-version.workspace = true
iota-config.workspace = true
iota-kvstore.workspace = true
iota-storage.workspace = true
iota-types.workspace = true
