[package]
name = "reviews_rating"
version = "0.0.1"
edition = "2024"

[dependencies]
Iota = { local = "../../../crates/iota-framework/packages/iota-framework", override = true }

[addresses]
reviews_rating = "0x0"
