[package]
name = "move-coverage"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Move VM code coverage"

[dependencies]
# external dependencies
anyhow.workspace = true
bcs.workspace = true
clap.workspace = true
codespan = { workspace = true, features = ["serialization"] }
colored.workspace = true
indexmap.workspace = true
petgraph.workspace = true
serde.workspace = true

# internal dependencies
move-abstract-interpreter.workspace = true
move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-ir-types.workspace = true

[features]
default = []
