[package]
name = "mvr-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
anyhow.workspace = true
thiserror.workspace = true
once_cell.workspace = true
regex = "1.11.1"
sui-sdk-types.workspace = true
