[package]
name = "typus"
version = "3.1.1"
published-at = "0x0624b66825d66821a57a49491fe1b31bc4f522459051a587aeb43828075f438a"
edition = "2024.alpha"

[dependencies.typus_nft]
git = "git@github.com:Typus-Lab/typus.git"
subdir = "typus_nft"
rev = "main"

[addresses]
typus = "0x4b0f4ee1a40ce37ec81c987cc4e76a665419e74b863319492fc7d26f708b835a"
fee_address = "0x03e3f1ca852358b50837758b5197fedf61e2ea69186c469595baa717560963f9"

# sui client upgrade --upgrade-capability 0xe8a7bb2dac645a6f57ed6711dfcb4c109b5dcf24be6c5db63ab0915b3e9c036c --gas 0x15466b6df9e2607fe961986efc33ab6147b10710c3cf3f2cbef2003e86122474 --gas-budget 1000000000 --serialize-unsigned-transaction > data.txt
