[package]
name = "shared_no_tto"
version = "0.0.1"
edition = "2024"

[dependencies]
Iota = { local = "../../../../crates/iota-framework/packages/iota-framework" }
common = { local = "../common" }

[addresses]
shared_no_tto = "0x0"
