[package]
name = "move-unit-test"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Unit testing framework for Move code"

[dependencies]
# external dependencies
anyhow.workspace = true
bcs.workspace = true
better_any.workspace = true
clap.workspace = true
codespan-reporting.workspace = true
colored.workspace = true
once_cell.workspace = true
rand.workspace = true
rayon.workspace = true
regex.workspace = true

# internal dependencies
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-ir-types.workspace = true
move-stdlib-natives = { workspace = true, features = ["testing"] }
move-symbol-pool.workspace = true
move-trace-format.workspace = true
move-vm-profiler.workspace = true
move-vm-runtime = { workspace = true, features = ["testing"] }
move-vm-test-utils.workspace = true
move-vm-types.workspace = true

[dev-dependencies]
# external dependencies
datatest-stable.workspace = true

# internal dependencies
move-stdlib = { workspace = true, features = ["testing"] }

[[bin]]
name = "move-unit-test"
path = "src/main.rs"

[[test]]
name = "move_unit_test_testsuite"
harness = false

[features]
tracing = []
