[package]
name = "account_dao"
edition = "2024"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.account_protocol]
local = "../../../move-framework/packages/protocol"

[dependencies.account_extensions]
local = "../../../move-framework/packages/extensions"
