[default]
extend-ignore-identifiers-re = [
  # Short git hashes
  "^[a-f0-9]{7}$",
  "^[a-f0-9]{12}$",
  # Base64
  "^[a-zA-Z0-9_]{43}$",
  "^[a-zA-Z0-9_]{44}$",
  "^[a-zA-Z0-9_]{47}$",
  "^[a-zA-Z0-9_]{49}$",
  "^[a-zA-Z0-9_]{56,}$",
]

extend-ignore-re = [
  # Truncated hex IDs (ex. "0x9...a9b")
  "0x[a-f0-9]\\.{3}[a-f0-9]{3}",
  # Block ignore for docs (e.g. { /* spellchecker:off */ } ... { /* spellchecker:on */ })
  # This can be expanded to other comment styles if needed
  "(?s)(\\{ /\\*)\\s*spellchecker:off.*?\\n\\s*(\\{ /\\*)\\s*spellchecker:on",
  # BCS octet documentation
  "[0-9]{2}OCTECT",
]

[type.hex-move]
extend-glob = ["hex.move"]
extend-words = { ba = "ba" }

[type.css]
extend-glob = ["*.css"]
extend-words = { wdth = "wdth" }

[default.extend-words]
# ordinal numbers (2nd, ...)
nd = "nd"
# random identifiers, variables, functions, ...
tto = "tto"
ser = "ser"
groth = "groth"
# Identity
AAS = "AAS"
# actual typos purposely used in tests
assing = "assing"
tring = "tring"
# better suggestions for typos
transferer = "transferrer"
# not in the correction dictionary
checkpoitn = "checkpoint"
typ = "typ"
# crates
bimap = "bimap"
# plurals
pendings = "pendings"

[default.extend-identifiers]
numer = "numer"

[files]
extend-exclude = [
  "pnpm-lock.yaml",
  "external-crates/*",
  "config-patch",
  "*.patch",
  "*.svg",
]
